### ISSUE TITLE
[FEATURE] Remake the music app (including looping of tracks, adding/removing of tracks in a playlist, etc)

### ISSUE THREAD

**Issue by Kade-github** [Kade-github/BombRushRadio#12]
I'm still thinking of a way to create a good menu for it, I might create another app on the phone that controls audio (turning on repeating and what not)

_Originally posted by @Kade-github in https://github.com/Kade-github/BombRushRadio/issues/9#issuecomment-1692824747_

**Comment by sekuza009** [comment]
Adding to this, even adding a shuffle for the custom songs would be great. As it stands right now it just plays them in alphabetical order.

**Comment by ChorusCory** [comment]
maybe add support for another metadata tag in a song that tells the mod what sample to loop it at?

**Comment by Kade-github** [comment]
Adding to this, Global Volume would be good to add to this.

**Comment by Kade-github** [comment]
I'll probably focus on this during the weekend, i'll see how much I can get done.

**Comment by Kade-github** [comment]
this was done via an update to the game.
