### ISSUE TITLE
Volume too low compared to Vanilla + Newer Versions not working for me

### ISSUE THREAD

**Issue by Liew60** [Kade-github/BombRushRadio#21]
I watched a tutorial on how to use one of the old versions, this being 1.2 but somehow the custom songs are very quiet compared to the  vanilla songs, I tried to look into it and I have assumed its probably the version that I was using. I decided to get 1.4 and try to test it again but for some reason when I tried to check the music, its just the vanilla ones. I am not sure if I have done it incorrectly or anything, I did what it said step by step and repeated more thoroughly but still to no avail.

I got Bepinex 5.4, I dragged the plugin folder and nothing happened. Did I do something wrong with the steps?

**Comment by Kade-github** [comment]
From what i've seen, the game's mixes (and songs) are mixed way louder than normal. I don't think this is a BRR issue.

**Comment by leopardheart982** [comment]
+1 for this. A global volume increase for imported songs would be welcome.

**Comment by andre409** [comment]
it won't load the 4th song or I tried to see if it was too big but it worked or I tried taking it off and putting it back on and it didn't work

**Comment by Kade-github** [comment]
> +1 for this. A global volume increase for imported songs would be welcome.

Yeah, i'll close this and add it to the main #12 remake issue.
