### ISSUE TITLE
 the other songs do not load

### ISSUE THREAD

**Issue by andre409** [Kade-github/BombRushRadio#27]
the game console always loads me the 3 songs I had put on even putting what you told me

**Comment by Kade-github** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/b17618fb-a608-4b88-8464-f48659226be1)
![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/566dbc17-247a-4f6f-9ec9-19b213bed23c)
![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/bfc0b0e3-e89c-4059-83d0-9a7045b4418b)
![image](https://github.com/Kade-github/BombRushRadio/assets/26305836/1bc27652-7753-46c9-8856-b7e5566959ca)

they work

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/603626b0-4f5e-4354-940e-b12d4aa94ffe)

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/9ff1c6bf-9b6c-4472-a1e5-23581f776416)

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/8b9c3391-5914-411e-8430-65670292a521)

**Comment by andre409** [comment]
@Kade-github
