### ISSUE TITLE
the other songs do not load

### ISSUE THREAD

**Issue by andre409** [Kade-github/BombRushRadio#28]

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/599e5324-5230-4768-835f-3a201e69090e)

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/21934887-740c-422a-80d5-d30620465309)

**Comment by andre409** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/74488429/c6de5974-cdcb-418c-8e2d-49e48266f32c)

**Comment by Kade-github** [comment]
only other thing I can say is putting them in BombRushCyberfunk_Data/StreamingAssets/Mods/BombRushRadio/Songs

as they work for me.

**Comment by andre409** [comment]
already done but it doesn't work

**Comment by andre409** [comment]
you can't send me files that reset the loading of songs?

**Comment by andre409** [comment]
can i have your mod files i try to use your files

**Comment by andre409** [comment]
?

**Comment by Kade-github** [comment]
im thinking this might be fixed in the latest branch's code (since it's not released it wont work for you)

i'll get to testing the current release branch in a bit, i'm quite busy atm.

**Comment by andre409** [comment]
ok

**Comment by Kade-github** [comment]
Can you check on this version? https://github.com/Kade-github/BombRushRadio/releases/tag/1.5

**Comment by andre409** [comment]
ok

**Comment by andre409** [comment]
He always uploads 3 songs for me

**Comment by andre409** [comment]
according to you I could have a mod that is blocking the loading of the other songs I thought about it but the only one that does something to the audio is the SFX

**Comment by andre409** [comment]
@Kade-github

**Comment by andre409** [comment]
or found the problem I was putting the songs in the wrong songs folder

**Comment by Kade-github** [comment]
cool
