### ISSUE TITLE
issue with my music or maybe just me

### ISSUE THREAD

**Issue by shrekondrugs** [Kade-github/BombRushRadio#35]
everytime i launch the game my radio doesnt work, i mean vanilla song does but modded one doesnt and idk why, is it because i didnt pay for it (the game), or because i got other mods, or both? i have tried both putting songs like in their own name or just in folders and nothing, please help, i made an account just for this!
![imagen_2023-12-03_170452987
](https://github.com/Kade-github/BombRushRadio/assets/152812063/8f0e765f-3d39-4e82-9bce-9b1a3bf4d6e2)

**Comment by shrekondrugs** [comment]
and also later on the console it says that the song loaded but it doesnt, i dont know if it could help to come up with a solution
![imagen_2023-12-03_170851085](https://github.com/Kade-github/BombRushRadio/assets/152812063/d1b616d1-8f2b-40c9-aecc-61d01f4c7c24)

**Comment by RagdollClash** [comment]
This issue occurs on outdated versions of the game. You can fix this by buying the game, which will ensure that the game is updated.
