### ISSUE TITLE
Are there prerequisites to get this to work?

### ISSUE THREAD

**Issue by KMHTech** [Kade-github/BombRushRadio#5]
Can we just install this using Thunderstore?
If not, then installing this using the instructions isn't working.

**Comment by Kade-github** [comment]
How are you installing this? There is a Thunderstore out right now, but it is legit a drag and drop into the main directory to get it installed.

**Comment by KMHTech** [comment]
did a drag and drop, with the bepinex included file
but its not picking up my songs ingame at all.
I even made sure the folder and song names are correct

**Comment by KMHTech** [comment]
the part that's confusing me, is that it says it will create these folders but they arent being created for me

**Comment by Kade-github** [comment]
so that means that isn't actually loading bepinex, can you screenshot me your main games folder? where the exe is.

**Comment by KMHTech** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/108137992/34dbc747-afa0-42ec-bc11-c8b53aa3e514)

**Comment by KMHTech** [comment]
I deleted the files, though I can reinstall them again.

**Comment by KMHTech** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/108137992/80a430eb-f2b9-4f7e-b8b3-e3c62851b645)

**Comment by KMHTech** [comment]
nope, nothing

**Comment by KMHTech** [comment]
![image](https://github.com/Kade-github/BombRushRadio/assets/108137992/0bec22c9-747b-45fc-9dc8-4b4d85656c1f)
This is what comes up in the window

**Comment by Kade-github** [comment]
you're on 5.4.21.

we only have a version out for 6.0 atm, i'll eventually release one for 5.24 but thats why it isn't loading.
