### ISSUE TITLE
Volume?

### ISSUE THREAD

**Issue by supersonic124** [Kade-github/BombRushRadio#9]
Any chance a volume option for custom songs could be added? Sometimes songs can be too low and turning up the in game option isn't the best because then the vanilla songs become way louder

**Comment by Kade-github** [comment]
I'm still thinking of a way to create a good menu for it, I might create another app on the phone that controls audio (turning on repeating and what not)

**Comment by Kade-github** [comment]
changed into this https://github.com/Kade-github/BombRushRadio/issues/12
